const Ziggy = {
    url: 'https://localhost',
    port: null,
    defaults: {},
    routes: {
        'sanctum.csrf-cookie': { uri: 'sanctum/csrf-cookie', methods: ['GET', 'HEAD'] },
        'log-viewer.hosts': { uri: 'logs/api/hosts', methods: ['GET', 'HEAD'] },
        'log-viewer.folders': { uri: 'logs/api/folders', methods: ['GET', 'HEAD'] },
        'log-viewer.folders.request-download': { uri: 'logs/api/folders/{folderIdentifier}/download/request', methods: ['GET', 'HEAD'], parameters: ['folderIdentifier'] },
        'log-viewer.folders.clear-cache': { uri: 'logs/api/folders/{folderIdentifier}/clear-cache', methods: ['POST'], parameters: ['folderIdentifier'] },
        'log-viewer.folders.delete': { uri: 'logs/api/folders/{folderIdentifier}', methods: ['DELETE'], parameters: ['folderIdentifier'] },
        'log-viewer.files': { uri: 'logs/api/files', methods: ['GET', 'HEAD'] },
        'log-viewer.files.request-download': { uri: 'logs/api/files/{fileIdentifier}/download/request', methods: ['GET', 'HEAD'], parameters: ['fileIdentifier'] },
        'log-viewer.files.clear-cache': { uri: 'logs/api/files/{fileIdentifier}/clear-cache', methods: ['POST'], parameters: ['fileIdentifier'] },
        'log-viewer.files.delete': { uri: 'logs/api/files/{fileIdentifier}', methods: ['DELETE'], parameters: ['fileIdentifier'] },
        'log-viewer.files.clear-cache-all': { uri: 'logs/api/clear-cache-all', methods: ['POST'] },
        'log-viewer.files.delete-multiple-files': { uri: 'logs/api/delete-multiple-files', methods: ['POST'] },
        'log-viewer.logs': { uri: 'logs/api/logs', methods: ['GET', 'HEAD'] },
        'log-viewer.folders.download': { uri: 'logs/api/folders/{folderIdentifier}/download', methods: ['GET', 'HEAD'], parameters: ['folderIdentifier'] },
        'log-viewer.files.download': { uri: 'logs/api/files/{fileIdentifier}/download', methods: ['GET', 'HEAD'], parameters: ['fileIdentifier'] },
        'log-viewer.index': { uri: 'logs/{view?}', methods: ['GET', 'HEAD'], wheres: { view: '(.*)' }, parameters: ['view'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email/{id}/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'password', methods: ['PUT'] },
        logout: { uri: 'logout', methods: ['POST'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        expenses: { uri: 'expenses', methods: ['GET', 'HEAD'] },
        'payment-methods': { uri: 'payment-methods', methods: ['GET', 'HEAD'] },
        'payment-methods.store': { uri: 'payment-methods', methods: ['POST'] },
        'payment-methods.update': { uri: 'payment-methods/{paymentMethod}', methods: ['PUT'], parameters: ['paymentMethod'], bindings: { paymentMethod: 'id' } },
        'payment-methods.destroy': { uri: 'payment-methods/{paymentMethod}', methods: ['DELETE'], parameters: ['paymentMethod'], bindings: { paymentMethod: 'id' } },
        investments: { uri: 'investments', methods: ['GET', 'HEAD'] },
        'investments.store': { uri: 'investments', methods: ['POST'] },
        'investments.update': { uri: 'investments/{investment}', methods: ['PUT'], parameters: ['investment'], bindings: { investment: 'id' } },
        'investments.destroy': { uri: 'investments/{investment}', methods: ['DELETE'], parameters: ['investment'], bindings: { investment: 'id' } },
        projects: { uri: 'projects', methods: ['GET', 'HEAD'] },
        'projects.store': { uri: 'projects', methods: ['POST'] },
        'projects.update': { uri: 'projects/{project}', methods: ['PUT'], parameters: ['project'], bindings: { project: 'id' } },
        'projects.destroy': { uri: 'projects/{project}', methods: ['DELETE'], parameters: ['project'], bindings: { project: 'id' } },
        services: { uri: 'services', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
        'storage.local': { uri: 'storage/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
